# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0002_auto_20170528_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_administrative_level', models.CharField(choices=[('local', 'Τοπικό(π.χ.πόλη, δήμος)'), ('regional', 'Περιφερειακό'), ('national', 'Εθνικό'), ('european', 'Ευρωπαϊκό'), ('international', 'Διεθνές')], default='local', max_length=250)),
                ('alternative_administrative_level', models.CharField(choices=[('local', 'Τοπικό(π.χ.πόλη, δήμος)'), ('regional', 'Περιφερειακό'), ('national', 'Εθνικό'), ('european', 'Ευρωπαϊκό'), ('international', 'Διεθνές')], default='local', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('cell_phone', models.CharField(max_length=250)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_user', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_administration', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicelandscape',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('number',)},
        ),
        migrations.DeleteModel(
            name='ServiceLandscape',
        ),
    ]
