# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0003_auto_20170529_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_channel', multiselectfield.db.fields.MultiSelectField(choices=[('portal', 'Διαδικτυακή πύλη'), ('telephone', 'Τηλεφωνικά'), ('postal', 'Ταχυδρομικά'), ('counter_desk', 'Γραφείο/κισέ'), ('dedicated_app', 'Ειδική εφαρμογή'), ('website_portal', 'Διαδίκτυο και/ή Διαδικτυακή πύλη')], max_length=150)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
