# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 16:35
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_deliverychannel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverychannel',
            name='delivery_channel',
        ),
        migrations.AddField(
            model_name='deliverychannel',
            name='digital_channel',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dedicated_app', 'Ειδική εφαρμογή'), ('website_portal', 'Διαδίκτυο και/ή Διαδικτυακή πύλη'), ('portal', 'Διαδικτυακή πύλη')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='deliverychannel',
            name='traditional_channel',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('counter_desk', 'Γραφείο/κισέ'), ('postal', 'Ταχυδρομικά'), ('telephone', 'Τηλεφωνικά')], max_length=150, null=True),
        ),
    ]
