# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0005_auto_20170605_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AccessibilityOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(blank=True, max_length=300, null=True)),
                ('score', models.IntegerField(null=0)),
            ],
        ),
        migrations.AddField(
            model_name='accessibility',
            name='accessibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.AccessibilityOption'),
        ),
        migrations.AddField(
            model_name='accessibility',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question'),
        ),
        migrations.AddField(
            model_name='accessibility',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
