# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20170605_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibility',
            name='accessibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.AccessibilityOption'),
        ),
    ]
