# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20170605_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.CharField(max_length=3),
        ),
    ]
