# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_auto_20170608_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='totalnumber',
            field=models.IntegerField(default=0, null=0),
            preserve_default=False,
        ),
    ]
