# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_question_totalnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='totalnumber',
        ),
    ]
