# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-10 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_question_maturity_scoring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='maturity_scoring',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=200),
        ),
    ]
