# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 13:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_auto_20170611_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('maturity_level', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_consumed_today', models.CharField(max_length=120)),
                ('reusing_of_services', models.CharField(blank=True, max_length=120, null=True)),
                ('processing_mode', models.CharField(blank=True, max_length=120, null=True)),
                ('push_pull_mechanisms', models.CharField(blank=True, max_length=120, null=True)),
                ('common_protocol_usage', models.CharField(blank=True, max_length=120, null=True)),
                ('reuse_of_network', models.CharField(blank=True, max_length=120, null=True)),
                ('semantic_alignment', models.CharField(blank=True, max_length=120, null=True)),
                ('exception_handling', models.CharField(blank=True, max_length=120, null=True)),
                ('certification', models.CharField(blank=True, max_length=120, null=True)),
                ('specification_process', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandscapingServiceConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landscaping_service_consumption', multiselectfield.db.fields.MultiSelectField(choices=[('business_analytics_service', 'Υπηρεσία Επιχειρηματικής Ανάλυσης'), ('authentication_service', 'Υπηρεσία Αυθεντικοποίησης'), ('metadata_management_service', 'Υπηρεσία Διαχείρισης Μεταδεδομένων'), ('e_signature_service', 'Υπηρεσία Ηλεκτρονικών Υπογραφών'), ('access_management_service', 'Υπηρεσία Διαχείρισης Πρόσβασης'), ('business_reporting_service', 'Υπηρεσία Αναφοράς Επιχειρήσεων'), ('document_management_service', 'Υπηρεσία Διαχείρισης Εγγράφων'), ('data_transformation_service', 'Υπηρεσία Μετασχηματισμού Δεδομένων'), ('networking_service', 'Υπηρεσία Δικτύωσης'), ('content_management_service', 'Υπηρεσία Διαχείρισης Περιεχομένου'), ('messaging_service', 'Yπηρεσία Μηνυμάτων'), ('data_exchange_service', 'Υπηρεσία Ανταλλαγής Δεδομένων'), ('records_management_service', 'Υπηρεσία Διαχείρισης Αρχείων'), ('hosting_service', 'Υπηρεσία Φιλοξενίας'), ('base_registry_information_source', 'Υπηρεσία Πληροφοριών Μητρώου'), ('e_payment_service', 'Υπηρεσία Ηλεκτρονικών Πληρωμών'), ('machine_translation_service', 'Υπηρεσία Αυτόματης Μετάφρασης'), ('logging_service', 'Υπηρεσία Σύνδεσης'), ('storage_service', 'Υπηρεσία Αποθήκευσης'), ('forms_management_service', 'Υπηρεσία Διαχείρισης Φορμών'), ('audio_visual_service', 'Υπηρεσία Οπτικοακουστικών Μέσων'), ('audit_service', 'Υπηρεσία Ελέγχου')], max_length=250, null=True)),
                ('consumed_service_maturity_level', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecificServicesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=150, null=True)),
                ('landscaping_service_consumption', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.LandscapingServiceConsumption')),
            ],
        ),
    ]
