# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 16:26
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0016_consumedservice_consumption_landscapingserviceconsumption_specificserviceslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landscapingserviceconsumption',
            name='landscaping_service_consumption',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('hosting_service', 'Υπηρεσία Φιλοξενίας'), ('machine_translation_service', 'Υπηρεσία Αυτόματης Μετάφρασης'), ('e_payment_service', 'Υπηρεσία Ηλεκτρονικών Πληρωμών'), ('e_signature_service', 'Υπηρεσία Ηλεκτρονικών Υπογραφών'), ('data_exchange_service', 'Υπηρεσία Ανταλλαγής Δεδομένων'), ('content_management_service', 'Υπηρεσία Διαχείρισης Περιεχομένου'), ('messaging_service', 'Yπηρεσία Μηνυμάτων'), ('networking_service', 'Υπηρεσία Δικτύωσης'), ('document_management_service', 'Υπηρεσία Διαχείρισης Εγγράφων'), ('base_registry_information_source', 'Υπηρεσία Πληροφοριών Μητρώου'), ('metadata_management_service', 'Υπηρεσία Διαχείρισης Μεταδεδομένων'), ('logging_service', 'Υπηρεσία Σύνδεσης'), ('storage_service', 'Υπηρεσία Αποθήκευσης'), ('authentication_service', 'Υπηρεσία Αυθεντικοποίησης'), ('access_management_service', 'Υπηρεσία Διαχείρισης Πρόσβασης'), ('business_analytics_service', 'Υπηρεσία Επιχειρηματικής Ανάλυσης'), ('data_transformation_service', 'Υπηρεσία Μετασχηματισμού Δεδομένων'), ('forms_management_service', 'Υπηρεσία Διαχείρισης Φορμών'), ('audit_service', 'Υπηρεσία Ελέγχου'), ('audio_visual_service', 'Υπηρεσία Οπτικοακουστικών Μέσων'), ('records_management_service', 'Υπηρεσία Διαχείρισης Αρχείων'), ('business_reporting_service', 'Υπηρεσία Αναφοράς Επιχειρήσεων')], max_length=250, null=True),
        ),
    ]
