# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0017_auto_20170611_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibility',
            name='maturityscoring',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='accessibility',
            name='accessibility_weight',
            field=models.FloatField(default=0.4),
        ),
        migrations.AlterField(
            model_name='accessibilityoption',
            name='score',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='landscapingserviceconsumption',
            name='landscaping_service_consumption',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('hosting_service', 'Υπηρεσία Φιλοξενίας'), ('audit_service', 'Υπηρεσία Ελέγχου'), ('access_management_service', 'Υπηρεσία Διαχείρισης Πρόσβασης'), ('content_management_service', 'Υπηρεσία Διαχείρισης Περιεχομένου'), ('data_exchange_service', 'Υπηρεσία Ανταλλαγής Δεδομένων'), ('audio_visual_service', 'Υπηρεσία Οπτικοακουστικών Μέσων'), ('storage_service', 'Υπηρεσία Αποθήκευσης'), ('networking_service', 'Υπηρεσία Δικτύωσης'), ('logging_service', 'Υπηρεσία Σύνδεσης'), ('document_management_service', 'Υπηρεσία Διαχείρισης Εγγράφων'), ('forms_management_service', 'Υπηρεσία Διαχείρισης Φορμών'), ('e_payment_service', 'Υπηρεσία Ηλεκτρονικών Πληρωμών'), ('business_reporting_service', 'Υπηρεσία Αναφοράς Επιχειρήσεων'), ('business_analytics_service', 'Υπηρεσία Επιχειρηματικής Ανάλυσης'), ('authentication_service', 'Υπηρεσία Αυθεντικοποίησης'), ('machine_translation_service', 'Υπηρεσία Αυτόματης Μετάφρασης'), ('metadata_management_service', 'Υπηρεσία Διαχείρισης Μεταδεδομένων'), ('data_transformation_service', 'Υπηρεσία Μετασχηματισμού Δεδομένων'), ('records_management_service', 'Υπηρεσία Διαχείρισης Αρχείων'), ('e_signature_service', 'Υπηρεσία Ηλεκτρονικών Υπογραφών'), ('base_registry_information_source', 'Υπηρεσία Πληροφοριών Μητρώου'), ('messaging_service', 'Yπηρεσία Μηνυμάτων')], max_length=250, null=True),
        ),
    ]
