# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 07:27
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_auto_20170613_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landscapingserviceconsumption',
            name='landscaping_service_consumption',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('e_payment_service', 'Υπηρεσία Ηλεκτρονικών Πληρωμών'), ('logging_service', 'Υπηρεσία Σύνδεσης'), ('data_transformation_service', 'Υπηρεσία Μετασχηματισμού Δεδομένων'), ('metadata_management_service', 'Υπηρεσία Διαχείρισης Μεταδεδομένων'), ('forms_management_service', 'Υπηρεσία Διαχείρισης Φορμών'), ('audit_service', 'Υπηρεσία Ελέγχου'), ('records_management_service', 'Υπηρεσία Διαχείρισης Αρχείων'), ('base_registry_information_source', 'Υπηρεσία Πληροφοριών Μητρώου'), ('e_signature_service', 'Υπηρεσία Ηλεκτρονικών Υπογραφών'), ('audio_visual_service', 'Υπηρεσία Οπτικοακουστικών Μέσων'), ('document_management_service', 'Υπηρεσία Διαχείρισης Εγγράφων'), ('access_management_service', 'Υπηρεσία Διαχείρισης Πρόσβασης'), ('messaging_service', 'Yπηρεσία Μηνυμάτων'), ('machine_translation_service', 'Υπηρεσία Αυτόματης Μετάφρασης'), ('authentication_service', 'Υπηρεσία Αυθεντικοποίησης'), ('business_reporting_service', 'Υπηρεσία Αναφοράς Επιχειρήσεων'), ('storage_service', 'Υπηρεσία Αποθήκευσης'), ('hosting_service', 'Υπηρεσία Φιλοξενίας'), ('business_analytics_service', 'Υπηρεσία Επιχειρηματικής Ανάλυσης'), ('content_management_service', 'Υπηρεσία Διαχείρισης Περιεχομένου'), ('networking_service', 'Υπηρεσία Δικτύωσης'), ('data_exchange_service', 'Υπηρεσία Ανταλλαγής Δεδομένων')], max_length=250, null=True),
        ),
    ]
