# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0019_auto_20170614_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='maturity',
            field=models.FloatField(default=0, null=0),
        ),
        migrations.AlterField(
            model_name='landscapingserviceconsumption',
            name='landscaping_service_consumption',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('hosting_service', 'Υπηρεσία Φιλοξενίας'), ('base_registry_information_source', 'Υπηρεσία Πληροφοριών Μητρώου'), ('content_management_service', 'Υπηρεσία Διαχείρισης Περιεχομένου'), ('messaging_service', 'Yπηρεσία Μηνυμάτων'), ('data_exchange_service', 'Υπηρεσία Ανταλλαγής Δεδομένων'), ('logging_service', 'Υπηρεσία Σύνδεσης'), ('access_management_service', 'Υπηρεσία Διαχείρισης Πρόσβασης'), ('metadata_management_service', 'Υπηρεσία Διαχείρισης Μεταδεδομένων'), ('audio_visual_service', 'Υπηρεσία Οπτικοακουστικών Μέσων'), ('records_management_service', 'Υπηρεσία Διαχείρισης Αρχείων'), ('forms_management_service', 'Υπηρεσία Διαχείρισης Φορμών'), ('business_reporting_service', 'Υπηρεσία Αναφοράς Επιχειρήσεων'), ('document_management_service', 'Υπηρεσία Διαχείρισης Εγγράφων'), ('storage_service', 'Υπηρεσία Αποθήκευσης'), ('audit_service', 'Υπηρεσία Ελέγχου'), ('networking_service', 'Υπηρεσία Δικτύωσης'), ('data_transformation_service', 'Υπηρεσία Μετασχηματισμού Δεδομένων'), ('e_signature_service', 'Υπηρεσία Ηλεκτρονικών Υπογραφών'), ('business_analytics_service', 'Υπηρεσία Επιχειρηματικής Ανάλυσης'), ('authentication_service', 'Υπηρεσία Αυθεντικοποίησης'), ('e_payment_service', 'Υπηρεσία Ηλεκτρονικών Πληρωμών'), ('machine_translation_service', 'Υπηρεσία Αυτόματης Μετάφρασης')], max_length=250, null=True),
        ),
    ]
