# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 07:33
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0020_auto_20170614_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='maturity',
        ),
        migrations.AlterField(
            model_name='landscapingserviceconsumption',
            name='landscaping_service_consumption',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('e_payment_service', 'Υπηρεσία Ηλεκτρονικών Πληρωμών'), ('storage_service', 'Υπηρεσία Αποθήκευσης'), ('business_reporting_service', 'Υπηρεσία Αναφοράς Επιχειρήσεων'), ('metadata_management_service', 'Υπηρεσία Διαχείρισης Μεταδεδομένων'), ('data_exchange_service', 'Υπηρεσία Ανταλλαγής Δεδομένων'), ('messaging_service', 'Yπηρεσία Μηνυμάτων'), ('data_transformation_service', 'Υπηρεσία Μετασχηματισμού Δεδομένων'), ('business_analytics_service', 'Υπηρεσία Επιχειρηματικής Ανάλυσης'), ('forms_management_service', 'Υπηρεσία Διαχείρισης Φορμών'), ('authentication_service', 'Υπηρεσία Αυθεντικοποίησης'), ('audit_service', 'Υπηρεσία Ελέγχου'), ('content_management_service', 'Υπηρεσία Διαχείρισης Περιεχομένου'), ('machine_translation_service', 'Υπηρεσία Αυτόματης Μετάφρασης'), ('networking_service', 'Υπηρεσία Δικτύωσης'), ('access_management_service', 'Υπηρεσία Διαχείρισης Πρόσβασης'), ('logging_service', 'Υπηρεσία Σύνδεσης'), ('e_signature_service', 'Υπηρεσία Ηλεκτρονικών Υπογραφών'), ('hosting_service', 'Υπηρεσία Φιλοξενίας'), ('audio_visual_service', 'Υπηρεσία Οπτικοακουστικών Μέσων'), ('records_management_service', 'Υπηρεσία Διαχείρισης Αρχείων'), ('base_registry_information_source', 'Υπηρεσία Πληροφοριών Μητρώου'), ('document_management_service', 'Υπηρεσία Διαχείρισης Εγγράφων')], max_length=250, null=True),
        ),
    ]
