# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 20:04
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0021_auto_20170614_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativelevel',
            name='alternative_administrative_level',
        ),
        migrations.RemoveField(
            model_name='administrativelevel',
            name='main_administrative_level',
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='administrative_level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('local', 'Τοπικό(π.χ.πόλη, δήμος)'), ('regional', 'Περιφερειακό'), ('natinal', 'Εθνικό'), ('european', 'Ευρωπαϊκό'), ('international', 'Διεθνές')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landscapingserviceconsumption',
            name='landscaping_service_consumption',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('e_signature_service', 'Υπηρεσία Ηλεκτρονικών Υπογραφών'), ('audit_service', 'Υπηρεσία Ελέγχου'), ('document_management_service', 'Υπηρεσία Διαχείρισης Εγγράφων'), ('storage_service', 'Υπηρεσία Αποθήκευσης'), ('authentication_service', 'Υπηρεσία Αυθεντικοποίησης'), ('content_management_service', 'Υπηρεσία Διαχείρισης Περιεχομένου'), ('hosting_service', 'Υπηρεσία Φιλοξενίας'), ('access_management_service', 'Υπηρεσία Διαχείρισης Πρόσβασης'), ('business_analytics_service', 'Υπηρεσία Επιχειρηματικής Ανάλυσης'), ('metadata_management_service', 'Υπηρεσία Διαχείρισης Μεταδεδομένων'), ('messaging_service', 'Yπηρεσία Μηνυμάτων'), ('records_management_service', 'Υπηρεσία Διαχείρισης Αρχείων'), ('data_exchange_service', 'Υπηρεσία Ανταλλαγής Δεδομένων'), ('base_registry_information_source', 'Υπηρεσία Πληροφοριών Μητρώου'), ('machine_translation_service', 'Υπηρεσία Αυτόματης Μετάφρασης'), ('business_reporting_service', 'Υπηρεσία Αναφοράς Επιχειρήσεων'), ('audio_visual_service', 'Υπηρεσία Οπτικοακουστικών Μέσων'), ('logging_service', 'Υπηρεσία Σύνδεσης'), ('forms_management_service', 'Υπηρεσία Διαχείρισης Φορμών'), ('e_payment_service', 'Υπηρεσία Ηλεκτρονικών Πληρωμών'), ('data_transformation_service', 'Υπηρεσία Μετασχηματισμού Δεδομένων'), ('networking_service', 'Υπηρεσία Δικτύωσης')], max_length=250, null=True),
        ),
    ]
