# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0025_auto_20170618_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='maturityscore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
