# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0026_question_maturityscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='maturityscore',
        ),
        migrations.AddField(
            model_name='answer',
            name='maturity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
