# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0027_auto_20170621_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='maturity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
