# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0028_auto_20170621_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('question_id',)},
        ),
    ]
