# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0029_auto_20170625_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuseandsharing',
            name='maturity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
