# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0030_reuseandsharing_maturity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
    ]
