# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0031_auto_20170709_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, max_length=910, null=True),
        ),
        migrations.AlterField(
            model_name='servicedescription',
            name='service_description',
            field=models.TextField(max_length=250),
        ),
    ]
