# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 08:25
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0032_auto_20170710_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativelevel',
            name='administrative_level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('local', 'Τοπικό(π.χ.πόλη, δήμος)'), ('regional', 'Περιφερειακό'), ('national', 'Εθνικό'), ('european', 'Ευρωπαϊκό'), ('international', 'Διεθνές')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='cell_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
