# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0033_auto_20170711_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativelevel',
            name='administrative_level',
            field=models.CharField(blank=True, choices=[('local', 'Τοπικό(π.χ.πόλη, δήμος)'), ('regional', 'Περιφερειακό'), ('national', 'Εθνικό'), ('european', 'Ευρωπαϊκό'), ('international', 'Διεθνές')], max_length=1, null=True),
        ),
    ]
