# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0038_auto_20170714_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceowner',
            name='user',
        ),
        migrations.AlterField(
            model_name='serviceowner',
            name='service_owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.ServiceOwnerOption'),
            preserve_default=False,
        ),
    ]
