# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0039_auto_20170714_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceowner',
            name='service_owner',
        ),
        migrations.AddField(
            model_name='serviceowner',
            name='public_administration',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ServiceOwnerOption',
        ),
    ]
