# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0041_auto_20170715_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceowner',
            old_name='serviceowner',
            new_name='service_owner',
        ),
    ]
