# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0042_auto_20170715_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
